version: "3.8"
services:
  mysql:
    container_name: mysql_db
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data/MySQL:/var/liv/mysql 